/**
 * Build-time script: tokenize all book texts with Kuromoji
 * Run: npx tsx scripts/generate-tokens.ts
 */
import kuromoji from 'kuromoji';
import * as path from 'path';
import * as fs from 'fs';

// We can't easily import TS with path aliases, so read books.ts and extract content
const __dirname = path.dirname(new URL(import.meta.url).pathname);
const booksPath = path.resolve(__dirname, '../src/data/books.ts');
const booksSource = fs.readFileSync(booksPath, 'utf-8');

// Extract book IDs and content mapping from the books array
type Difficulty = 'simplified' | 'intermediate' | 'original';

interface BookContent {
  id: string;
  content: Record<Difficulty, string>;
}

// Parse the variable assignments for book content
function extractBookContents(): BookContent[] {
  const books: BookContent[] = [];
  
  // Match variable assignments like: const momotaroSimplified = `...`;
  const varPattern = /const\s+(\w+)\s*=\s*`([^`]*)`/g;
  const vars: Record<string, string> = {};
  let match;
  while ((match = varPattern.exec(booksSource)) !== null) {
    vars[match[1]] = match[2];
  }
  
  // Match book objects to get IDs and content variable references
  const bookPattern = /id:\s*'([^']+)'[\s\S]*?content:\s*\{\s*simplified:\s*(\w+)\s*,\s*intermediate:\s*(\w+)\s*,\s*original:\s*(\w+)\s*\}/g;
  while ((match = bookPattern.exec(booksSource)) !== null) {
    const [, id, simpVar, intVar, origVar] = match;
    books.push({
      id,
      content: {
        simplified: vars[simpVar] || '',
        intermediate: vars[intVar] || '',
        original: vars[origVar] || '',
      }
    });
  }
  
  return books;
}

interface KuromojiToken {
  surface_form: string;
  pos: string;
  pos_detail_1: string;
  basic_form: string;
  reading: string;
  pronunciation: string;
}

interface OutputToken {
  t: string;        // text (surface_form)
  j: boolean;       // isJapanese
  r?: string;       // reading (katakana from kuromoji)
  b?: string;       // baseForm (basic_form / dictionary form)
  p?: string;       // pos (part of speech)
}

function isJapanesePos(pos: string): boolean {
  // Kuromoji POS tags that are "Japanese content" (not punctuation/symbols)
  const contentPos = ['名詞', '動詞', '形容詞', '形容動詞', '副詞', '連体詞', '接続詞', '感動詞', '助動詞', '助詞', '接頭詞', 'フィラー'];
  return contentPos.includes(pos);
}

function katakanaToHiragana(str: string): string {
  return str.replace(/[\u30A1-\u30F6]/g, (ch) =>
    String.fromCharCode(ch.charCodeAt(0) - 0x60)
  );
}

async function main() {
  const books = extractBookContents();
  console.log(`Found ${books.length} books`);
  
  // Initialize kuromoji
  const dictPath = path.resolve(__dirname, '../node_modules/kuromoji/dict');
  
  const tokenizer = await new Promise<kuromoji.Tokenizer<KuromojiToken>>((resolve, reject) => {
    kuromoji.builder({ dicPath: dictPath }).build((err: Error | null, tokenizer: any) => {
      if (err) reject(err);
      else resolve(tokenizer);
    });
  });
  
  console.log('Kuromoji loaded');
  
  const allTokens: Record<string, Record<string, OutputToken[]>> = {};
  
  for (const book of books) {
    allTokens[book.id] = {};
    for (const diff of ['simplified', 'intermediate', 'original'] as Difficulty[]) {
      const text = book.content[diff];
      if (!text) continue;
      
      const kTokens: KuromojiToken[] = tokenizer.tokenize(text);
      const outputTokens: OutputToken[] = [];
      
      for (const kt of kTokens) {
        const isJp = isJapanesePos(kt.pos);
        const token: OutputToken = {
          t: kt.surface_form,
          j: isJp,
        };
        
        if (isJp) {
          // Add reading (convert to hiragana)
          if (kt.reading && kt.reading !== '*') {
            token.r = katakanaToHiragana(kt.reading);
          }
          // Add base form if different from surface
          if (kt.basic_form && kt.basic_form !== '*' && kt.basic_form !== kt.surface_form) {
            token.b = kt.basic_form;
          }
          // Add POS
          if (kt.pos && kt.pos !== '*') {
            token.p = kt.pos;
            // Add detail for verbs/adjectives
            if (kt.pos_detail_1 && kt.pos_detail_1 !== '*') {
              token.p += '/' + kt.pos_detail_1;
            }
          }
        }
        
        outputTokens.push(token);
      }
      
      allTokens[book.id][diff] = outputTokens;
      console.log(`  ${book.id}/${diff}: ${outputTokens.length} tokens`);
    }
  }
  
  // Generate output file
  const outputPath = path.resolve(__dirname, '../src/data/book-tokens.ts');
  
  const output = `// Auto-generated by scripts/generate-tokens.ts using Kuromoji
// Do not edit manually - regenerate with: npx tsx scripts/generate-tokens.ts

export interface BookToken {
  /** surface text */
  t: string;
  /** is Japanese content (not punctuation) */
  j: boolean;
  /** reading in hiragana */
  r?: string;
  /** base/dictionary form (only if different from surface) */
  b?: string;
  /** part of speech (e.g. "動詞/自立", "形容詞/自立") */
  p?: string;
}

export const bookTokens: Record<string, Record<string, BookToken[]>> = ${JSON.stringify(allTokens, null, 0)};
`;
  
  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log(`\nWritten to ${outputPath} (${(Buffer.byteLength(output) / 1024).toFixed(0)} KB)`);
}

main().catch(console.error);
