-- Renaming grammar slugs
UPDATE public.grammar_examples SET pattern_slug = 'masu-stem-申す' WHERE pattern_slug = 'o-masu-stem-申す' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'masu-stem-申す');
UPDATE public.saved_grammar SET item_id = 'masu-stem-申す' WHERE item_id = 'o-masu-stem-申す' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'masu-stem-申す');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'o-masu-stem-申す';
DELETE FROM public.saved_grammar WHERE item_id = 'o-masu-stem-申す';
UPDATE public.grammar_examples SET pattern_slug = 'masu-stem-たい-と思う' WHERE pattern_slug = 'v-tai-form-と思う' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'masu-stem-たい-と思う');
UPDATE public.saved_grammar SET item_id = 'masu-stem-たい-と思う' WHERE item_id = 'v-tai-form-と思う' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'masu-stem-たい-と思う');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'v-tai-form-と思う';
DELETE FROM public.saved_grammar WHERE item_id = 'v-tai-form-と思う';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-うちに' WHERE pattern_slug = 'うちに' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-うちに');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-うちに' WHERE item_id = 'うちに' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-うちに');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'うちに';
DELETE FROM public.saved_grammar WHERE item_id = 'うちに';
UPDATE public.grammar_examples SET pattern_slug = 'masu-stem-いたす' WHERE pattern_slug = 'お-masu-stem-いたす' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'masu-stem-いたす');
UPDATE public.saved_grammar SET item_id = 'masu-stem-いたす' WHERE item_id = 'お-masu-stem-いたす' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'masu-stem-いたす');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'お-masu-stem-いたす';
DELETE FROM public.saved_grammar WHERE item_id = 'お-masu-stem-いたす';
UPDATE public.grammar_examples SET pattern_slug = 'masu-stem-する' WHERE pattern_slug = 'お-masu-stem-する-したい' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'masu-stem-する');
UPDATE public.saved_grammar SET item_id = 'masu-stem-する' WHERE item_id = 'お-masu-stem-する-したい' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'masu-stem-する');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'お-masu-stem-する-したい';
DELETE FROM public.saved_grammar WHERE item_id = 'お-masu-stem-する-したい';
UPDATE public.grammar_examples SET pattern_slug = 'masu-stem-になる' WHERE pattern_slug = 'お-masu-stem-になる' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'masu-stem-になる');
UPDATE public.saved_grammar SET item_id = 'masu-stem-になる' WHERE item_id = 'お-masu-stem-になる' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'masu-stem-になる');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'お-masu-stem-になる';
DELETE FROM public.saved_grammar WHERE item_id = 'お-masu-stem-になる';
UPDATE public.grammar_examples SET pattern_slug = 'masu-stem-申し上げる' WHERE pattern_slug = 'お-masu-stem-申し上げる-申す' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'masu-stem-申し上げる');
UPDATE public.saved_grammar SET item_id = 'masu-stem-申し上げる' WHERE item_id = 'お-masu-stem-申し上げる-申す' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'masu-stem-申し上げる');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'お-masu-stem-申し上げる-申す';
DELETE FROM public.saved_grammar WHERE item_id = 'お-masu-stem-申し上げる-申す';
UPDATE public.grammar_examples SET pattern_slug = 'clause-がゆえに' WHERE pattern_slug = 'がゆえに-が故に' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'clause-がゆえに');
UPDATE public.saved_grammar SET item_id = 'clause-がゆえに' WHERE item_id = 'がゆえに-が故に' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'clause-がゆえに');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'がゆえに-が故に';
DELETE FROM public.saved_grammar WHERE item_id = 'がゆえに-が故に';
UPDATE public.grammar_examples SET pattern_slug = 'noun-が見える-が聞こえる' WHERE pattern_slug = 'が見える-が聞こえる' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-が見える-が聞こえる');
UPDATE public.saved_grammar SET item_id = 'noun-が見える-が聞こえる' WHERE item_id = 'が見える-が聞こえる' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-が見える-が聞こえる');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'が見える-が聞こえる';
DELETE FROM public.saved_grammar WHERE item_id = 'が見える-が聞こえる';
UPDATE public.grammar_examples SET pattern_slug = 'noun-さえ-conditional-form-ばいい' WHERE pattern_slug = 'さえ-ばいい' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-さえ-conditional-form-ばいい');
UPDATE public.saved_grammar SET item_id = 'noun-さえ-conditional-form-ばいい' WHERE item_id = 'さえ-ばいい' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-さえ-conditional-form-ばいい');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'さえ-ばいい';
DELETE FROM public.saved_grammar WHERE item_id = 'さえ-ばいい';
UPDATE public.grammar_examples SET pattern_slug = 'plain-negative' WHERE pattern_slug = 'さらに-plain-negative' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'plain-negative');
UPDATE public.saved_grammar SET item_id = 'plain-negative' WHERE item_id = 'さらに-plain-negative' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'plain-negative');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'さらに-plain-negative';
DELETE FROM public.saved_grammar WHERE item_id = 'さらに-plain-negative';
UPDATE public.grammar_examples SET pattern_slug = 'noun-しか-plain-negative' WHERE pattern_slug = 'しか-ない' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-しか-plain-negative');
UPDATE public.saved_grammar SET item_id = 'noun-しか-plain-negative' WHERE item_id = 'しか-ない' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-しか-plain-negative');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'しか-ない';
DELETE FROM public.saved_grammar WHERE item_id = 'しか-ない';
UPDATE public.grammar_examples SET pattern_slug = 'number-ずつ' WHERE pattern_slug = 'ずつ' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'number-ずつ');
UPDATE public.saved_grammar SET item_id = 'number-ずつ' WHERE item_id = 'ずつ' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'number-ずつ');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ずつ';
DELETE FROM public.saved_grammar WHERE item_id = 'ずつ';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-そうだ-hearsay' WHERE pattern_slug = 'そうです-hearsay' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-そうだ-hearsay');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-そうだ-hearsay' WHERE item_id = 'そうです-hearsay' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-そうだ-hearsay');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'そうです-hearsay';
DELETE FROM public.saved_grammar WHERE item_id = 'そうです-hearsay';
UPDATE public.grammar_examples SET pattern_slug = 'te-form-ある' WHERE pattern_slug = 'てある-てあります' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'te-form-ある');
UPDATE public.saved_grammar SET item_id = 'te-form-ある' WHERE item_id = 'てある-てあります' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'te-form-ある');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'てある-てあります';
DELETE FROM public.saved_grammar WHERE item_id = 'てある-てあります';
UPDATE public.grammar_examples SET pattern_slug = 'te-form-おく' WHERE pattern_slug = 'ておく' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'te-form-おく');
UPDATE public.saved_grammar SET item_id = 'te-form-おく' WHERE item_id = 'ておく' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'te-form-おく');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ておく';
DELETE FROM public.saved_grammar WHERE item_id = 'ておく';
UPDATE public.grammar_examples SET pattern_slug = 'te-form-おく' WHERE pattern_slug = 'ておく-て置く' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'te-form-おく');
UPDATE public.saved_grammar SET item_id = 'te-form-おく' WHERE item_id = 'ておく-て置く' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'te-form-おく');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ておく-て置く';
DELETE FROM public.saved_grammar WHERE item_id = 'ておく-て置く';
UPDATE public.grammar_examples SET pattern_slug = 'te-form-しまう' WHERE pattern_slug = 'てしまう-てしまった' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'te-form-しまう');
UPDATE public.saved_grammar SET item_id = 'te-form-しまう' WHERE item_id = 'てしまう-てしまった' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'te-form-しまう');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'てしまう-てしまった';
DELETE FROM public.saved_grammar WHERE item_id = 'てしまう-てしまった';
UPDATE public.grammar_examples SET pattern_slug = 'te-form-も' WHERE pattern_slug = 'ても-でも' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'te-form-も');
UPDATE public.saved_grammar SET item_id = 'te-form-も' WHERE item_id = 'ても-でも' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'te-form-も');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ても-でも';
DELETE FROM public.saved_grammar WHERE item_id = 'ても-でも';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-と' WHERE pattern_slug = 'と-conditional-form' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-と');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-と' WHERE item_id = 'と-conditional-form' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-と');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'と-conditional-form';
DELETE FROM public.saved_grammar WHERE item_id = 'と-conditional-form';
UPDATE public.grammar_examples SET pattern_slug = 'noun-ともなれば' WHERE pattern_slug = 'ともなれば' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-ともなれば');
UPDATE public.saved_grammar SET item_id = 'noun-ともなれば' WHERE item_id = 'ともなれば' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-ともなれば');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ともなれば';
DELETE FROM public.saved_grammar WHERE item_id = 'ともなれば';
UPDATE public.grammar_examples SET pattern_slug = 'noun-ともなれば' WHERE pattern_slug = 'ともなれば-ともなると' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-ともなれば');
UPDATE public.saved_grammar SET item_id = 'noun-ともなれば' WHERE item_id = 'ともなれば-ともなると' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-ともなれば');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ともなれば-ともなると';
DELETE FROM public.saved_grammar WHERE item_id = 'ともなれば-ともなると';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-だろう' WHERE pattern_slug = 'どんなに-dictionary-form-だろう' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-だろう');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-だろう' WHERE item_id = 'どんなに-dictionary-form-だろう' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-だろう');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'どんなに-dictionary-form-だろう';
DELETE FROM public.saved_grammar WHERE item_id = 'どんなに-dictionary-form-だろう';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-な-prohibition' WHERE pattern_slug = 'な-だな' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-な-prohibition');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-な-prohibition' WHERE item_id = 'な-だな' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-な-prohibition');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'な-だな';
DELETE FROM public.saved_grammar WHERE item_id = 'な-だな';
UPDATE public.grammar_examples SET pattern_slug = 'plain-negative' WHERE pattern_slug = 'なかなか-plain-negative' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'plain-negative');
UPDATE public.saved_grammar SET item_id = 'plain-negative' WHERE item_id = 'なかなか-plain-negative' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'plain-negative');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'なかなか-plain-negative';
DELETE FROM public.saved_grammar WHERE item_id = 'なかなか-plain-negative';
UPDATE public.grammar_examples SET pattern_slug = 'clause-と思う' WHERE pattern_slug = 'に思う-とおmoy' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'clause-と思う');
UPDATE public.saved_grammar SET item_id = 'clause-と思う' WHERE item_id = 'に思う-とおmoy' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'clause-と思う');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'に思う-とおmoy';
DELETE FROM public.saved_grammar WHERE item_id = 'に思う-とおmoy';
UPDATE public.grammar_examples SET pattern_slug = 'plain-negative-ぬ' WHERE pattern_slug = 'ぬ-ず' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'plain-negative-ぬ');
UPDATE public.saved_grammar SET item_id = 'plain-negative-ぬ' WHERE item_id = 'ぬ-ず' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'plain-negative-ぬ');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ぬ-ず';
DELETE FROM public.saved_grammar WHERE item_id = 'ぬ-ず';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-の' WHERE pattern_slug = 'の-nominalizer' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-の');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-の' WHERE item_id = 'の-nominalizer' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-の');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'の-nominalizer';
DELETE FROM public.saved_grammar WHERE item_id = 'の-nominalizer';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-のに' WHERE pattern_slug = 'のに' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-のに');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-のに' WHERE item_id = 'のに' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-のに');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'のに';
DELETE FROM public.saved_grammar WHERE item_id = 'のに';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-はず' WHERE pattern_slug = 'はず-筈' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-はず');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-はず' WHERE item_id = 'はず-筈' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-はず');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'はず-筈';
DELETE FROM public.saved_grammar WHERE item_id = 'はず-筈';
UPDATE public.grammar_examples SET pattern_slug = 'conditional-form-ば' WHERE pattern_slug = 'ば' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'conditional-form-ば');
UPDATE public.saved_grammar SET item_id = 'conditional-form-ば' WHERE item_id = 'ば' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'conditional-form-ば');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ば';
DELETE FROM public.saved_grammar WHERE item_id = 'ば';
UPDATE public.grammar_examples SET pattern_slug = 'noun-ほど' WHERE pattern_slug = 'ほど' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-ほど');
UPDATE public.saved_grammar SET item_id = 'noun-ほど' WHERE item_id = 'ほど' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-ほど');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ほど';
DELETE FROM public.saved_grammar WHERE item_id = 'ほど';
UPDATE public.grammar_examples SET pattern_slug = 'noun-ほど' WHERE pattern_slug = 'ほど-ほどに' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-ほど');
UPDATE public.saved_grammar SET item_id = 'noun-ほど' WHERE item_id = 'ほど-ほどに' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-ほど');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ほど-ほどに';
DELETE FROM public.saved_grammar WHERE item_id = 'ほど-ほどに';
UPDATE public.grammar_examples SET pattern_slug = 'まいる-humble-verb' WHERE pattern_slug = 'まいりました-humble-verb' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'まいる-humble-verb');
UPDATE public.saved_grammar SET item_id = 'まいる-humble-verb' WHERE item_id = 'まいりました-humble-verb' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'まいる-humble-verb');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'まいりました-humble-verb';
DELETE FROM public.saved_grammar WHERE item_id = 'まいりました-humble-verb';
UPDATE public.grammar_examples SET pattern_slug = 'noun-のように' WHERE pattern_slug = 'まるで-noun-のように-まるで-dictionary-form-かのように' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun-のように');
UPDATE public.saved_grammar SET item_id = 'noun-のように' WHERE item_id = 'まるで-noun-のように-まるで-dictionary-form-かのように' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun-のように');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'まるで-noun-のように-まるで-dictionary-form-かのように';
DELETE FROM public.saved_grammar WHERE item_id = 'まるで-noun-のように-まるで-dictionary-form-かのように';
UPDATE public.grammar_examples SET pattern_slug = 'clause' WHERE pattern_slug = 'みるみる-clause' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'clause');
UPDATE public.saved_grammar SET item_id = 'clause' WHERE item_id = 'みるみる-clause' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'clause');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'みるみる-clause';
DELETE FROM public.saved_grammar WHERE item_id = 'みるみる-clause';
UPDATE public.grammar_examples SET pattern_slug = 'clause-なら' WHERE pattern_slug = 'もし-clause-なら' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'clause-なら');
UPDATE public.saved_grammar SET item_id = 'clause-なら' WHERE item_id = 'もし-clause-なら' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'clause-なら');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'もし-clause-なら';
DELETE FROM public.saved_grammar WHERE item_id = 'もし-clause-なら';
UPDATE public.grammar_examples SET pattern_slug = 'clause' WHERE pattern_slug = 'やっと-clause' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'clause');
UPDATE public.saved_grammar SET item_id = 'clause' WHERE item_id = 'やっと-clause' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'clause');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'やっと-clause';
DELETE FROM public.saved_grammar WHERE item_id = 'やっと-clause';
UPDATE public.grammar_examples SET pattern_slug = 'volitional-form' WHERE pattern_slug = 'よう-volitional-form' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'volitional-form');
UPDATE public.saved_grammar SET item_id = 'volitional-form' WHERE item_id = 'よう-volitional-form' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'volitional-form');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'よう-volitional-form';
DELETE FROM public.saved_grammar WHERE item_id = 'よう-volitional-form';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-ようだ' WHERE pattern_slug = 'ようです' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-ようだ');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-ようだ' WHERE item_id = 'ようです' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-ようだ');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ようです';
DELETE FROM public.saved_grammar WHERE item_id = 'ようです';
UPDATE public.grammar_examples SET pattern_slug = 'volitional-form-とする' WHERE pattern_slug = 'ようとする-おうとする' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'volitional-form-とする');
UPDATE public.saved_grammar SET item_id = 'volitional-form-とする' WHERE item_id = 'ようとする-おうとする' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'volitional-form-とする');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'ようとする-おうとする';
DELETE FROM public.saved_grammar WHERE item_id = 'ようとする-おうとする';
UPDATE public.grammar_examples SET pattern_slug = 'dictionary-form-らしい' WHERE pattern_slug = 'らしい' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'dictionary-form-らしい');
UPDATE public.saved_grammar SET item_id = 'dictionary-form-らしい' WHERE item_id = 'らしい' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'dictionary-form-らしい');
DELETE FROM public.grammar_examples WHERE pattern_slug = 'らしい';
DELETE FROM public.saved_grammar WHERE item_id = 'らしい';
UPDATE public.grammar_examples SET pattern_slug = 'noun' WHERE pattern_slug = '何とも言えない-noun' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'noun');
UPDATE public.saved_grammar SET item_id = 'noun' WHERE item_id = '何とも言えない-noun' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'noun');
DELETE FROM public.grammar_examples WHERE pattern_slug = '何とも言えない-noun';
DELETE FROM public.saved_grammar WHERE item_id = '何とも言えない-noun';
UPDATE public.grammar_examples SET pattern_slug = 'adjective-verb' WHERE pattern_slug = '余りに-adjective-verb' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'adjective-verb');
UPDATE public.saved_grammar SET item_id = 'adjective-verb' WHERE item_id = '余りに-adjective-verb' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'adjective-verb');
DELETE FROM public.grammar_examples WHERE pattern_slug = '余りに-adjective-verb';
DELETE FROM public.saved_grammar WHERE item_id = '余りに-adjective-verb';
UPDATE public.grammar_examples SET pattern_slug = 'plain-negative' WHERE pattern_slug = '全く-plain-negative' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'plain-negative');
UPDATE public.saved_grammar SET item_id = 'plain-negative' WHERE item_id = '全く-plain-negative' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'plain-negative');
DELETE FROM public.grammar_examples WHERE pattern_slug = '全く-plain-negative';
DELETE FROM public.saved_grammar WHERE item_id = '全く-plain-negative';
UPDATE public.grammar_examples SET pattern_slug = 'question-word-か' WHERE pattern_slug = '疑問詞-か' AND NOT EXISTS (SELECT 1 FROM public.grammar_examples WHERE pattern_slug = 'question-word-か');
UPDATE public.saved_grammar SET item_id = 'question-word-か' WHERE item_id = '疑問詞-か' AND NOT EXISTS (SELECT 1 FROM public.saved_grammar WHERE item_id = 'question-word-か');
DELETE FROM public.grammar_examples WHERE pattern_slug = '疑問詞-か';
DELETE FROM public.saved_grammar WHERE item_id = '疑問詞-か';
