// Auto-generated by scripts/generate-tokens.ts
// Pre-computed Japanese-token counts per (key, difficulty).
export const tokenWordCounts: Record<string, Record<string, number>> = {
 "a-aki": {
 "simplified": 313,
 "intermediate": 456,
 "original": 655
 },
 "konbini-ningen": {
 "simplified": 601,
 "intermediate": 903,
 "original": 890
 },
 "konbini-ningen__ch1": {
 "simplified": 601,
 "intermediate": 903,
 "original": 890
 },
 "konbini-ningen__ch2": {
 "simplified": 797,
 "intermediate": 1038,
 "original": 957
 },
 "konbini-ningen__ch3": {
 "simplified": 664,
 "intermediate": 933,
 "original": 830
 },
 "konbini-ningen__ch4": {
 "simplified": 564,
 "intermediate": 912,
 "original": 930
 },
 "konbini-ningen__ch5": {
 "simplified": 479,
 "intermediate": 897,
 "original": 870
 },
 "konbini-ningen__ch6": {
 "simplified": 605,
 "intermediate": 918,
 "original": 836
 },
 "kumo-no-ito": {
 "simplified": 317,
 "intermediate": 678,
 "original": 1368
 },
 "rashomon": {
 "simplified": 477,
 "intermediate": 795,
 "original": 2829
 },
 "hashire-merosu": {
 "simplified": 1016,
 "intermediate": 2967,
 "original": 4424
 },
 "lemon": {
 "simplified": 823,
 "intermediate": 1275,
 "original": 2387
 },
 "hana": {
 "simplified": 731,
 "intermediate": 1254,
 "original": 3014
 },
 "matsu": {
 "simplified": 376,
 "intermediate": 438,
 "original": 923
 },
 "asa": {
 "simplified": 744,
 "intermediate": 1311,
 "original": 1350
 },
 "gyofukuki": {
 "simplified": 675,
 "intermediate": 1112,
 "original": 2479
 },
 "sakura": {
 "simplified": 587,
 "intermediate": 799,
 "original": 859
 },
 "urashima": {
 "simplified": 586,
 "intermediate": 1710,
 "original": 2287
 }
};
